CEC_YAMAHA_POWER_VERSION = v0.9.3
CEC_YAMAHA_POWER_SITE = $(call github,jsouthworth,cec_yamaha_power,$(CEC_YAMAHA_POWER_VERSION))
CEC_YAMAHA_POWER_LICENSE = 0BSD
CEC_YAMAHA_POWER_LICENSE_FILES = LICENSE

$(eval $(golang-package))
